### ISSUE TITLE
Feature Request: Include direct link's to Bridge DAI from Ethereum and Wrap xDai... and include a link to this guide

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-abc-dashboard#10]
[Bridge DAI from Ethereum
](https://bridge.gnosischain.com/)

[Wrap xDai](https://wrapeth.com/)

Link to this guide: https://token-engineering-commons.gitbook.io/tec-handbook/how-to-purchase-usdtec

**Comment by mateodaza** [comment]
Solved in #15
