### ISSUE TITLE
We should show the balance (and locked balance) of TEC and the Balance of wxDAI

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-abc-dashboard#12]
<img width="471" alt="Screen Shot 2022-10-05 at 6 25 20 PM" src="https://user-images.githubusercontent.com/14945613/194187232-2e826172-5161-49a4-aba8-1d14057f2224.png">
I assume this is the right place to put it... under the tokens

This is how it is done in the simple app, best to stay consistent 

<img width="256" alt="Screen Shot 2022-10-05 at 6 28 24 PM" src="https://user-images.githubusercontent.com/14945613/194187397-3d1eafba-a617-49eb-bef7-5ed5c1617e8f.png">

<img width="287" alt="Screen Shot 2022-10-05 at 6 28 13 PM" src="https://user-images.githubusercontent.com/14945613/194187416-0184818c-1137-4ed3-ac04-2b03c8803dd3.png">

**Comment by rodricastillo9013** [comment]
![Screenshot 2022-11-22 at 18 34 04](https://user-images.githubusercontent.com/61791380/203382573-d8c05838-aa62-4eb4-b14a-46985a5fc945.png)
https://www.figma.com/file/b6kx4mkaHxzq4TPzaI1eRY/TEC-Dapps?node-id=8553%3A9005&t=0wYaBP2a1uofkzOr-1 i thinks this its good option to show this info!

**Comment by mateodaza** [comment]
Solved in #15
