### ISSUE TITLE
Gear should be an image of a curve, so it's more clear

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-abc-dashboard#3]
<img width="142" alt="Screen Shot 2022-10-04 at 5 23 39 PM" src="https://user-images.githubusercontent.com/14945613/193948483-1a38116c-af8f-41c7-aa96-2296466e0534.png">

Rodri is the designer right? prob an issue for him

**Comment by rodricastillo9013** [comment]
![Screenshot 2022-11-09 at 11 46 13](https://user-images.githubusercontent.com/61791380/200810264-812284fc-d4d7-41d9-8f3b-86f0c5be0049.png)
https://www.figma.com/file/b6kx4mkaHxzq4TPzaI1eRY/TEC-Dapps?node-id=8377%3A6789

**Comment by mateodaza** [comment]
solved in #15
