### ISSUE TITLE
New Mint price is wrong...  at least at low numbers

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-abc-dashboard#6]
<img width="197" alt="Screen Shot 2022-10-04 at 5 47 04 PM" src="https://user-images.githubusercontent.com/14945613/193950638-42788214-058b-4ef4-b6a0-64a67b650534.png">
<img width="1152" alt="Screen Shot 2022-10-04 at 5 47 02 PM" src="https://user-images.githubusercontent.com/14945613/193950639-a73f55ec-590f-4946-886e-07a6c461d1b1.png">

**Comment by mateodaza** [comment]
solved in commit [8b5d2d4](https://github.com/CommonsBuild/tec-abc-dashboard/commit/8b5d2d4d60bd7c467eef2dbb40821ac42ee48423)
