### ISSUE TITLE
It's weird that the lines move just slightly, lets fix that and change the color and make them solid

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-abc-dashboard#8]
https://user-images.githubusercontent.com/14945613/193951227-67843621-e4f7-4e0f-bc1d-e87b7319b71a.mp4

See how the horizontal dotted lines connected to the user move just slightly up and down when you click burn and mint... it is weird... also the fact that they are dotted makes the lines move too when you add the arrows... a few suggestions i would make.

1. Make the lines not move up and down

2. Make the lines just slightly thicker and solid, not dotted.

3. Make the Arrows more pronounced

4. Make the lines change color, make the burn lines be red and the mint lines be whatever color Rodri suggests

**Comment by rodricastillo9013** [comment]
![Screenshot 2022-11-09 at 11 37 47](https://user-images.githubusercontent.com/61791380/200808495-98decc54-7859-4b07-aba4-bc171f48deb9.png)

I think that the ideal would be to add some simple animation in the lines and when changing from Burn to mint. :)

**Comment by rodricastillo9013** [comment]
![Screenshot 2022-11-09 at 11 45 23](https://user-images.githubusercontent.com/61791380/200810074-a63e9f44-06a6-4fb8-8a15-9874feb446e0.png)

I think that the ideal would be to add some simple animation in the lines and when changing from Burn to mint.

**Comment by mateodaza** [comment]
Solved in #15
