### ISSUE TITLE
quick text edit: Should be "Common Pool" and "Reserve"

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-abc-dashboard#9]
<img width="517" alt="Screen Shot 2022-10-04 at 6 00 10 PM" src="https://user-images.githubusercontent.com/14945613/193951752-808d0ead-d81a-4ca5-bef4-75913e3ab189.png">

**Comment by rodricastillo9013** [comment]
![Graphic 2](https://user-images.githubusercontent.com/61791380/203373356-f4712ef3-17ce-442f-bb56-5c315d68a100.png)
![Graphic 1](https://user-images.githubusercontent.com/61791380/203373362-86df2a2c-1395-498c-a54d-f179c6d7112c.png)
Done

**Comment by mateodaza** [comment]
Solved in #15
